const questions = [
  {
    question: "Which energy source comes from the sun?",
    options: ["Solar", "Wind", "Coal", "Oil"],
    answer: "Solar",
    explanation:
      "Solar energy is harnessed from the sun's rays using photovoltaic panels. These panels convert sunlight directly into electricity through a process called the photovoltaic effect.  The photovoltaic effect occurs when sunlight strikes the solar panel, exciting electrons within the material. These excited electrons flow through the panel, generating an electric current.",
  },
  {
    question: "What is the primary source of wind energy?",
    options: ["Sun", "Water", "Wind", "Coal"],
    answer: "Wind",
    explanation:
      "Wind energy is generated by the movement of air masses across the Earth's surface. Wind turbines are designed to capture this kinetic energy of moving air. The blades of the turbine rotate as the wind blows, converting the wind's energy into mechanical energy that is then used to spin a generator and produce electricity.",
  },
  {
    question: "What is an example of a biofuel?",
    options: ["Gasoline", "Coal", "Ethanol", "Natural Gas"],
    answer: "Ethanol",
    explanation:
      "Biofuels are a type of renewable energy derived from organic matter, such as plants or animal waste. Ethanol is a common biofuel produced from the fermentation of sugars found in plants like corn or sugarcane.  The fermentation process breaks down the sugars into ethanol and carbon dioxide. The ethanol can then be burned in an engine to produce heat or converted into a transportation fuel.",
  },
  {
    question:
      "Which energy source is formed from the remains of plants and animals?",
    options: ["Wind", "Nuclear", "Fossil Fuels", "Hydroelectric"],
    answer: "Fossil Fuels",
    explanation:
      "Fossil fuels, such as coal, oil, and natural gas, are formed from the decomposed remains of plants and animals that lived millions of years ago. Over time, these organic materials were buried under layers of sediment and subjected to intense heat and pressure. This process transformed the organic matter into the fossil fuels we use today. Burning fossil fuels releases the stored chemical energy, but also generates pollutants like carbon dioxide.",
  },
  {
    question: "______ is the most common fossil fuel.",
    options: ["Natural Gas", "Oil", "Coal", "Petroleum"],
    answer: "Coal",
    explanation:
      "Coal is the most abundant fossil fuel on Earth. It is formed from the compressed remains of swamps and forests. Coal is primarily used in electricity generation, where it is burned to heat water and produce steam that drives turbines. However, burning coal releases significant greenhouse gases, contributing to climate change.",
  },
  {
    question: "Which energy source comes from splitting atoms?",
    options: ["Wind", "Solar", "Nuclear", "Hydroelectric"],
    answer: "Nuclear",
    explanation:
      "Nuclear energy is produced by a process called nuclear fission. In nuclear fission, the nucleus of an atom is split into smaller nuclei, releasing a tremendous amount of energy. Nuclear power plants use controlled nuclear fission reactions to generate heat, which is then used to produce steam that drives turbines and generates electricity.",
  },
  {
    question: "_______ is the primary component of natural gas.",
    options: ["Methane", "Ethane", "Propane", "Butane"],
    answer: "Methane",
    explanation:
      "Natural gas is a fossil fuel composed primarily of methane (CH4). Methane is the simplest hydrocarbon molecule and is the main component of natural gas, typically accounting for around 70% of its volume. Natural gas is a cleaner burning fossil fuel compared to coal or oil, but it still releases greenhouse gases when burned.",
  },
  {
    question: "Which energy source produces electricity by moving water?",
    options: ["Wind", "Coal", "Nuclear", "Hydroelectric"],
    answer: "Hydroelectric",
    explanation:
      "Hydroelectric power is a renewable energy source that utilizes the energy of moving water. Dams are constructed on rivers to create reservoirs that store water at a higher elevation. The release of water from the dam flows through turbines, converting the potential energy of the falling water into mechanical energy. The turbines then spin a generator, producing electricity.",
  },
  {
    question: "What is the main disadvantage of fossil fuels?",
    options: ["Renewable", "Clean", "Pollution", "Expensive"],
    answer: "Pollution",
    explanation:
      "The burning of fossil fuels releases a variety of pollutants into the atmosphere, including carbon",
  },
];

const quizContainer = document.getElementById("quiz");
const resultContainer = document.getElementById("result");
const submitButton = document.getElementById("submitBtn");

function displayQuiz() {
  const output = [];

  questions.forEach((question, index) => {
    const options = question.options
      .map(
        (option, i) => `
      <label>
        <input type="radio" name="question${index}" value="${option}">
        ${option}
      </label>
    `
      )
      .join("");

    output.push(`
      <div class="question">${index + 1}. ${question.question}</div>
      <div class="options">${options}</div>
    `);
  });

  quizContainer.innerHTML = output.join("");
}

function showResult() {
  const answerContainers = quizContainer.querySelectorAll(".options");
  let score = 0;
  let feedback = "";

  questions.forEach((question, index) => {
    const userAnswer = (
      answerContainers[index].querySelector(
        `input[name=question${index}]:checked`
      ) || {}
    ).value;

    if (userAnswer === question.answer) {
      score++;
    } else {
      feedback += `<p><strong>${question.question}</strong></p>`;
      feedback += `<p>Your answer: ${userAnswer}</p>`;
      feedback += `<p>Correct answer: ${question.answer}</p>`;
      feedback += `<p class="explanation">Explanation: ${question.explanation}</p>`;
    }
  });

  resultContainer.innerHTML = `You scored ${score} out of ${questions.length}. ${feedback}`;
}

displayQuiz();
submitButton.addEventListener("click", showResult);
